import = ["~/.config/alacritty/gruvbox-material.toml"]
[font]

normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 18.0

[window]

opacity = 1.0
padding = {x = 18, y = 16}
decorations = "Buttonless"
